apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vnc-proxy-pod.yaml
  - vnc-proxy-svc.yaml
  - vnc-proxy-sa.yaml
  - vnc-proxy-rbac.yaml
configMapGenerator:
  - name: vnc-proxy-cm
    literals:
      - LABEL_APP_KEY=app
      - LABEL_APP_VAL=vnc
      - LABEL_CLIENT_ID=client-id
      - TARGET_PORT="5901"
