apiVersion: v1
kind: Pod
metadata:
  name: vnc-proxy
  labels:
    app: vnc-proxy
spec:
  containers:
    - name: vnc-proxy
      image: vnc-proxy
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: vnc-proxy-cm
  serviceAccountName: vnc-proxy-sa
  automountServiceAccountToken: true
