apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vnc-proxy-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vnc-proxy-rolebinding
subjects:
  - kind: ServiceAccount
    name: vnc-proxy-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vnc-proxy-role
