apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vnc-network-policy
spec:
  podSelector:
    matchLabels:
      app: vnc
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: vnc-gateway
    ports:
    - protocol: TCP
      port: 3128
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
