apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: vnc-proxy
  name: vnc-proxy-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vnc
  name: vnc-pod-list-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vnc-proxy-allow-vnc-pod-list-rolebinding
  namespace: vnc
subjects:
  - namespace: vnc-proxy
    kind: ServiceAccount
    name: vnc-proxy-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vnc-pod-list-role
