apiVersion: v1
kind: Service
metadata:
  namespace: vnc
  name: proxy-svc
spec:
  selector:
    app: proxy
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
      protocol: TCP
  type: NodePort
