apiVersion: v1
kind: Service
metadata:
  namespace: vnc-proxy
  name: vnc-proxy
spec:
  selector:
    app: vnc-proxy
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
      protocol: TCP
  type: NodePort
