apiVersion: v1
kind: Pod
metadata:
  namespace: vnc-proxy
  name: vnc-proxy
  labels:
    app: vnc-proxy
spec:
  containers:
    - name: vnc-proxy
      image: proxy
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: vnc-proxy-secret
  serviceAccountName: vnc-proxy-sa
  automountServiceAccountToken: true
