---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vnc-gateway-cf-warp-secret
  namespace: smt-dev
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgBwBj3VYg7H3KBFhMwbyHMM3VFVFplIZWWxRn1yH9aByN0kF+Z0bB5SmU5LTRw8ROQU6mwwl8Byr9aPjuKh9f3dbBSB2Uf8yMCAgD4OTs1XDWttV2f2m1kzpDsNN5rSo/NZ1BRRLluFihUl+LhOfu1U/UrK04OP3g6riIlvF7z2wVc2v4NsekJFf6jVszOgwingObD/YExBN1UrzU60zn2PbYDhbiSz+NPr3vaXQpVJk4lPe4wEC0JGlq0DK4UNeHuLAZPKQ+2wIaXWO+GzT99vNaiz/ydQ9hOpc4eauWMlFJvaFvatLmIDxUDU3g/t/WRVuNj30OXuYwMs5uUOHzOrmtn0XXmMNmpNwSr/CO8WD8x6OgOWPTDzDgRNZivNfgiwifSeK81gmK47GNOVQQzOwRZCDZoD6mwFxb4p4PomsYY6PRMLgHFqdM59bWAg8exGwjc9GX70msX/gFXYe5csIWyouh9Lc5bq43wLpOFisBSYdj1hY16ItHLrxu9OY9cNoc5vvml6CQSTFSsz9XwGrCIiTadgzy2V1YV0RT+6fB3v5pGI01oT+vjvKoA9NIC7WANLnt3++jPYKa9SqzY1a4U1UMiFTVqWwrMULo3UVjoBaUPHzcxA3qHRyrgjpNqOBM0AVAj9Ljr9/PJFUDRl5jWpPJV3QTDXLYgQAziw1zToe74ze6waDGep64U7UBJCv/b5SLcVnG7jEvv0
    WIREGUARD_PRIVATE_KEY: AgByRW/USbhYdsVtkOidI5LyF+xyyhqTOGs/15FuSZdqyxYqqZOp5kG1HnAhorWH2RC7Pfa1ohfHn4hoGMulKiyzTgv5zZ9mfxLa0NKEFy/h+PpexWScJU1Of9D6abvpFpc9l+rTUkJT5O75xziyQTNbIiqYzSEYzsh+6VXrsE6iMGcmoIYfLxQULk2sbIgEnTO9FWTOd6lM8pS/Bw0WuGprFcBZEWJjec27U1PEx5Lah0l4SFee75kIhUVCqX5q/o6HtX1D1nq4EOQ5WVWKzSfo2ANtvOai0ttStSOsootuhPTu3UgWNV8jXpWLpZk+AdBiFzbj0GjiMbg2JuZktDrb3nG1HFEozuMRLMo4gNtiGOZ8M8GyhTqsmZdoHTl5qI/3SaI73BDCuBi/6ksL3f6Fa06EeHzuupY8vQijFQ1h8NjwQuPkAhgAXjMjhMidxzuD+/valZviJkJ+zeU1TXIS9ikMFvwYSP6U7RqfpUiSLqGJ3kM9ZKTRG1Z4eSRF4ADZYnYrTe98aDf7DlNfDDajabekVm5h9VtR4jody5+MmO/KPjzITz9/WDdIP5QV2gaFVGwpf8ng+p1dFpJ01/JGjjUZ7fX9t/1nDvMglh+dgAbajvEiL2U11XTBn5grIQb3lStH3LsdBCMZnCalw2EvYnqVId3dUKP8f7YjHg6T7oeqOtia3FjUVn54QIPTf9P1N/qa/+T/tXFcFD2NRV1kJHFr+7Ao1ySBJVEfPGu1sFxCMTyxrachPfhIZA==
  template:
    metadata:
      name: vnc-gateway-cf-warp-secret
      namespace: smt-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smt-secret
  namespace: smt-dev
spec:
  encryptedData:
    .env: AgB3r5URUACu//flhUZNLpYpaenokNx8oCy677fUo5+qzyhIqfXHyfFTOXUtgY4SDmrdmmzd94ILZZ2MAvMW+OMc1iZhkTLD6NgnL6TodMd3AtSsCNAGiJ1De66vV7Go/dfbSz7ds8ncfYeQVIhd7gtOE9Wx5MP/4SLX0XcpyqSdNqufz7oZYfMmz4Eo0Vqx8FAe8sTYX9iPjobCguBjx1+e4ziT6kHJPIq+jNgplPxM3c6M26ih488Lb7PYH8rmYU/pETi9cnr1f+EcoFUBYwghHv6UfoNvMAwmCunsLMfg5tSCl5HHN1m7yaVRm5RQd8TLL+7I2wvXxj0AvyzybYN7kresyoblImr5Abe8alf5EbwM601NOL0PfdeiTNZezDSdwxheIdFnMi3AVOkt8pk46s+vJq5zPVXIsHNlv0LtiYFDh06OniZrvKhKqVPGff9Y75anrEgUhgm+DIIMJXExW1kUeGHcqPuL3NKiCFRjzqGQAXpGh4NsxrespTeEROCXzU4q/QDVw6cYiCirQAIJKu2dw/Hl6pOsb+jqbDBKBfsX84kRi6MFxj0xDVHsuLYILLMUeuSpd3IQMd2kISZl2vyRY1KRSyfCbLhI6fipXDhvCG9lxxzSCMpXi9Bo97PVdzwWoe1twt3QzagkQKJ6N7UcjY+TjA7nWtGBv56QLslk5UiMA+davm/r9SMERNCE4kbOzqy7RuPOC5aQs3u90MF4wKeSKNi2WY9QLsdVQHs5pWUD2FapFi4IgEevyatrIBBub4X/+OVjNg5rPzCubMDvEMaE84t2aPrG+l5/PLGK4iW90dAjVtaQwXMLhYLbz93NnBdNMDNS8Y9sIm1kXUjx6VJbdL4kJSyfM+APIry7k8moN32si1l6SnnoimJICbIno2cj27kGS04IFgyHU05iB9L4+w68Mctkmy/7lcR2HoYZ0Rqchly1DyUjQ5lyLoLfmOw4AVJab7COkBHYzg==
  template:
    metadata:
      name: smt-secret
      namespace: smt-dev
    type: Opaque
