apiVersion: v1
kind: Service
metadata:
  namespace: vnc-gateway
  name: vnc-gateway
  labels:
    app: vnc-gateway
spec:
  selector:
    app: vnc-gateway
  ports:
    - port: 3128
      targetPort: 3128
      protocol: TCP
  type: ClusterIP
