root = "."
tmp_dir = "tmp"

# main.go를 기준으로 서버를 실행
[build]
cmd = "go build -o ./tmp/main ./main.go"
bin = "tmp/main"
log = "air_errors.log"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "docker"]
exclude_regex = ["_test.go"]

# 파일 변경 감지 설정
[watcher]
include_ext = ["go", "toml", "yaml"]
exclude_dir = ["tmp", "vendor"]

# 서버 실행
[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
