apiVersion: apps/v1
kind: Deployment
metadata:
  name: smt
spec:
  selector:
    matchLabels:
      app: smt
  template:
    metadata:
      labels:
        app: smt
    spec:
      containers:
        - name: smt
          image: smt
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: smt-env
              mountPath: /app/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: smt-env
          secret:
            secretName: smt-secret
      serviceAccountName: smt-sa
      automountServiceAccountToken: true
